import type {
  OHLCData,
  Strategy,
  BacktestResult,
  Trade,
  PerformanceMetrics,
  EquityPoint,
  Condition
} from '../types';
import type { IndicatorCondition } from '../types';
import type { TradingDate } from './date-utils';
import { isValidTradingDate, daysBetweenTradingDates } from './date-utils';
import { IndicatorEngine } from './indicators';
import { MetricsCalculator } from './metrics';
import { CleanBacktestEngine } from './clean-backtest';

/**
 * Position represents an open trade
 */
interface Position {
  id: string;
  entryDate: TradingDate; // Use TradingDate string
  entryPrice: number;
  quantity: number;
  entryIndex: number;
  stopLoss?: number;
  takeProfit?: number;
  maxHoldDays?: number;
}

/**
 * Signal represents entry/exit signals generated by strategy conditions
 */
interface Signal {
  type: 'entry' | 'exit';
  date: TradingDate; // Use TradingDate string
  price: number;
  index: number;
  reason?: string;
}

/**
 * BacktestEngine - Core backtesting algorithm that processes OHLC data chronologically
 */
export class BacktestEngine {
  private data: OHLCData[];
  private strategy: Strategy;
  private indicators: Map<string, number[]> = new Map();
  private signals: Signal[] = [];
  private trades: Trade[] = [];
  private equity: EquityPoint[] = [];
  private currentCapital: number;
  private currentPosition: Position | null = null;

  constructor(data: OHLCData[], strategy: Strategy) {
    this.data = data;
    this.strategy = strategy;
    this.currentCapital = strategy.riskManagement.initialCapital;

    this.validateInputs();
    this.calculateIndicators();
  }

  /**
   * Run the complete backtest
   */
  public runBacktest(): BacktestResult {
    this.resetState();
    this.processDataChronologically();
    this.closeOpenPosition();
    this.logIBSStatistics();

    const metrics = this.calculatePerformanceMetrics();

    // Create simplified result
    const result: BacktestResult = {
      trades: this.trades,
      metrics,
      equity: this.equity,
      insights: []
    };

    return result;
  }

  /**
   * Reset backtest state
   */
  private resetState(): void {
    this.signals = [];
    this.trades = [];
    this.equity = [];
    this.currentCapital = this.strategy.riskManagement.initialCapital;
    this.currentPosition = null;
  }

  /**
   * Process OHLC data chronologically
   */
  private processDataChronologically(): void {
    for (let i = 0; i < this.data.length; i++) {
      const bar = this.data[i];

      // Check for exit signals first (if we have a position)
      if (this.currentPosition) {
        this.checkExitConditions(i, bar);
      }

      // Check for entry signals (if we don't have a position)
      if (!this.currentPosition) {
        this.checkEntryConditions(i, bar);
      }

      // Update equity curve
      this.updateEquityCurve(i, bar);
    }
  }

  /**
   * Check entry conditions for the current bar
   */
  private checkEntryConditions(index: number, bar: OHLCData): void {
    if (this.evaluateConditions(this.strategy.entryConditions, index)) {
      this.enterPosition(index, bar);
    }
  }

  /**
   * Check exit conditions for the current bar
   */
  private checkExitConditions(index: number, bar: OHLCData): void {
    if (!this.currentPosition) return;

    let exitReason: string | null = null;
    let exitPrice = bar.close;

    // Для IBS стратегии: IBS + maxHoldDays, но также учитываем опциональные SL/TP если включены
    if (this.strategy.id === 'ibs-mean-reversion' || this.strategy.type === 'ibs-mean-reversion') {
      // Проверяем Stop Loss / Take Profit если включены
      const useSL = !!this.strategy.riskManagement.useStopLoss;
      const useTP = !!this.strategy.riskManagement.useTakeProfit;
      if (useSL && this.currentPosition.stopLoss && bar.low <= this.currentPosition.stopLoss) {
        exitReason = 'stop_loss';
        exitPrice = this.currentPosition.stopLoss;
      } else if (useTP && this.currentPosition.takeProfit && bar.high >= this.currentPosition.takeProfit) {
        exitReason = 'take_profit';
        exitPrice = this.currentPosition.takeProfit;
      }
      // 1. Проверяем IBS условие выхода
      if (!exitReason && this.evaluateConditions(this.strategy.exitConditions, index)) {
        exitReason = 'ibs_signal';
      }
      // 2. Проверяем максимальное время удержания
      else if (!exitReason && this.currentPosition.maxHoldDays) {
        const daysDiff = daysBetweenTradingDates(this.currentPosition.entryDate, bar.date);
        if (daysDiff >= this.currentPosition.maxHoldDays) {
          exitReason = 'max_hold_days';
        }
      }
    } else {
      // Для других стратегий - полная логика
      if (this.evaluateConditions(this.strategy.exitConditions, index)) {
        exitReason = 'signal';
      }
      else if (this.currentPosition.stopLoss && bar.low <= this.currentPosition.stopLoss) {
        exitReason = 'stop_loss';
        exitPrice = this.currentPosition.stopLoss;
      }
      else if (this.currentPosition.takeProfit && bar.high >= this.currentPosition.takeProfit) {
        exitReason = 'take_profit';
        exitPrice = this.currentPosition.takeProfit;
      }
      else if (this.currentPosition.maxHoldDays) {
        const daysDiff = daysBetweenTradingDates(this.currentPosition.entryDate, bar.date);
        if (daysDiff >= this.currentPosition.maxHoldDays) {
          exitReason = 'max_hold_days';
        }
      }
    }

    if (exitReason) {
      this.exitPosition(index, bar, exitPrice, exitReason);
    }
  }

  /**
   * Enter a new position
   */
  private enterPosition(index: number, bar: OHLCData): void {
    const entryPrice = this.calculateEntryPrice(bar);
    const quantity = this.calculatePositionSize(entryPrice);

    if (quantity <= 0) return;

    // Apply slippage (отключено для IBS стратегии)
    const slippageAdjustedPrice = (this.strategy.id === 'ibs-mean-reversion' || this.strategy.type === 'ibs-mean-reversion')
      ? entryPrice
      : entryPrice * (1 + this.strategy.riskManagement.slippage);

    // Calculate commission on entry
    const entryCommission = this.calculateCommission(quantity * slippageAdjustedPrice);

    // Check if we have enough capital
    const totalCost = (quantity * slippageAdjustedPrice) + entryCommission;
    if (totalCost > this.currentCapital) {
      return; // Not enough capital
    }

    // Create position
    this.currentPosition = {
      id: `trade-${Date.now()}-${index}`,
      entryDate: bar.date,
      entryPrice: slippageAdjustedPrice,
      quantity,
      entryIndex: index,
      // Для IBS стратегии используем SL/TP только если включены флаги
      stopLoss: (this.strategy.id === 'ibs-mean-reversion' || this.strategy.type === 'ibs-mean-reversion')
        ? (this.strategy.riskManagement.useStopLoss ? this.calculateStopLoss(slippageAdjustedPrice) : undefined)
        : this.calculateStopLoss(slippageAdjustedPrice),
      takeProfit: (this.strategy.id === 'ibs-mean-reversion' || this.strategy.type === 'ibs-mean-reversion')
        ? (this.strategy.riskManagement.useTakeProfit ? this.calculateTakeProfit(slippageAdjustedPrice) : undefined)
        : this.calculateTakeProfit(slippageAdjustedPrice),
      maxHoldDays: ((): number => {
        const paramMax = this.strategy.parameters.maxHoldDays;
        const riskMax = this.strategy.riskManagement.maxHoldDays;
        if (typeof paramMax === 'number') return paramMax;
        if (typeof riskMax === 'number') return riskMax;
        return 30;
      })()
    };

    // Update capital - subtract the total cost
    this.currentCapital -= totalCost;

    // Record signal
    this.signals.push({
      type: 'entry',
      date: bar.date,
      price: slippageAdjustedPrice,
      index,
      reason: 'strategy_signal'
    });
  }

  /**
   * Exit current position
   */
  private exitPosition(index: number, bar: OHLCData, exitPrice: number, exitReason: string): void {
    if (!this.currentPosition) return;

    // Apply slippage (отключено для IBS стратегии)
    const slippageAdjustedPrice = (this.strategy.id === 'ibs-mean-reversion' || this.strategy.type === 'ibs-mean-reversion')
      ? exitPrice
      : exitPrice * (1 - this.strategy.riskManagement.slippage);

    // Calculate commission on exit only (entry commission was already deducted from capital)
    const exitCommission = this.calculateCommission(this.currentPosition.quantity * slippageAdjustedPrice);

    // Calculate P&L correctly - entry commission already accounted for in capital
    const grossProceeds = this.currentPosition.quantity * slippageAdjustedPrice;
    const grossCost = this.currentPosition.quantity * this.currentPosition.entryPrice;
    const totalCommissions = exitCommission; // Only exit commission for P&L calculation

    // Net P&L = (Exit Value - Entry Value) - Total Commissions
    const pnl = (grossProceeds - grossCost) - totalCommissions;

    // Percentage return based on initial investment (entry commission already included in capital deduction)
    const entryCommission = this.calculateCommission(grossCost);
    const initialInvestment = grossCost + entryCommission;
    const pnlPercent = (pnl / initialInvestment) * 100;

    // Calculate trade duration
    const duration = daysBetweenTradingDates(this.currentPosition.entryDate, bar.date);

    // Debug: проверяем причину выхода и инвестиции

    // Create trade record with detailed information
    const trade: Trade = {
      id: this.currentPosition.id,
      entryDate: this.currentPosition.entryDate,
      exitDate: bar.date,
      entryPrice: this.currentPosition.entryPrice,
      exitPrice: slippageAdjustedPrice,
      quantity: this.currentPosition.quantity,
      pnl,
      pnlPercent,
      duration,
      exitReason,
      context: {
        marketConditions: 'normal',
        indicatorValues: this.getIndicatorValues(index),
        volatility: this.calculateVolatility(index),
        trend: this.calculateTrend(index),
        // Add detailed calculation info for debugging
        grossProceeds,
        grossCost,
        totalCommissions,
        initialInvestment,
        stopLoss: this.currentPosition.stopLoss,
        takeProfit: this.currentPosition.takeProfit
      }
    };

    this.trades.push(trade);



    // Update capital correctly  
    // At entry: capital -= (quantity * entryPrice + entryCommission)
    // At exit: capital += (quantity * exitPrice - exitCommission)
    this.currentCapital += grossProceeds - exitCommission;


    // Add current capital to trade context
    if (trade.context) {
      (trade.context as any).currentCapitalAfterExit = this.currentCapital;
    }

    // Record signal
    this.signals.push({
      type: 'exit',
      date: bar.date,
      price: slippageAdjustedPrice,
      index,
      reason: exitReason
    });

    // Clear position
    this.currentPosition = null;
  }

  /**
   * Close any open position at the end of data
   */
  private closeOpenPosition(): void {
    if (this.currentPosition && this.data.length > 0) {
      const lastBar = this.data[this.data.length - 1];
      this.exitPosition(this.data.length - 1, lastBar, lastBar.close, 'end_of_data');
    }
  }

  /**
   * Calculate position size based on strategy settings
   */
  private calculatePositionSize(price: number): number {
    const { riskManagement } = this.strategy;

    // Calculate position size accounting for commissions and available capital
    const capitalUsagePercent = riskManagement.capitalUsage || 100;
    const availableAmount = (this.currentCapital * capitalUsagePercent) / 100;

    // Estimate commission rate to calculate affordable quantity
    const estimatedCommissionRate = this.calculateCommissionRate();
    const effectivePrice = price * (1 + estimatedCommissionRate); // Price including commission
    const quantity = Math.floor(availableAmount / effectivePrice);

    // Verify we have enough capital for actual total cost
    const actualCost = quantity * price;
    const actualCommission = this.calculateCommission(actualCost);
    const totalCost = actualCost + actualCommission;

    if (totalCost > this.currentCapital) {
      // Reduce quantity to fit available capital
      const adjustedQuantity = Math.floor((this.currentCapital - actualCommission) / price);
      return Math.max(0, adjustedQuantity);
    }


    return quantity;
  }

  /**
   * Calculate commission rate for position sizing estimation
   */
  private calculateCommissionRate(): number {
    const { commission } = this.strategy.riskManagement;

    switch (commission.type) {
      case 'fixed': {
        // For fixed commission, estimate based on average trade size
        const averageTradeSize = this.currentCapital * 0.1; // Assume 10% average position
        return (commission.fixed || 0) / averageTradeSize;
      }

      case 'percentage':
        return (commission.percentage || 0) / 100;

      case 'combined': {
        // Estimate combined rate
        const averageTradeSize2 = this.currentCapital * 0.1;
        const fixedPart = (commission.fixed || 0) / averageTradeSize2;
        const percentagePart = (commission.percentage || 0) / 100;
        return fixedPart + percentagePart;
      }

      default:
        return 0.001; // Default 0.1% commission rate
    }
  }

  /**
   * Calculate commission based on strategy settings
   */
  private calculateCommission(tradeValue: number): number {
    const { commission } = this.strategy.riskManagement;

    switch (commission.type) {
      case 'fixed':
        return commission.fixed || 0;

      case 'percentage':
        return tradeValue * ((commission.percentage || 0) / 100);

      case 'combined': {
        const fixedPart = commission.fixed || 0;
        const percentagePart = tradeValue * ((commission.percentage || 0) / 100);
        return fixedPart + percentagePart;
      }

      default:
        return 0;
    }
  }

  /**
   * Calculate stop loss price
   */
  private calculateStopLoss(entryPrice: number): number | undefined {
    const { stopLoss } = this.strategy.riskManagement;
    if (!stopLoss) return undefined;

    // Stop loss should ALWAYS be below entry price for long positions
    return entryPrice * (1 - Math.abs(stopLoss) / 100);
  }

  /**
   * Calculate take profit price
   */
  private calculateTakeProfit(entryPrice: number): number | undefined {
    const { takeProfit } = this.strategy.riskManagement;
    if (!takeProfit) return undefined;

    // Take profit should ALWAYS be above entry price for long positions
    return entryPrice * (1 + Math.abs(takeProfit) / 100);
  }

  /**
   * Calculate entry price (could be open, close, or other logic)
   */
  private calculateEntryPrice(bar: OHLCData): number {
    // For simplicity, use the close price
    // In a more sophisticated system, this could be configurable
    return bar.close;
  }

  /**
   * Evaluate a set of conditions for the current bar
   */
  private evaluateConditions(conditions: Condition[], index: number): boolean {
    if (conditions.length === 0) return false;

    // For now, use AND logic (all conditions must be true)
    // In a more sophisticated system, this could be configurable
    return conditions.every(condition => this.evaluateCondition(condition, index));
  }

  /**
   * Evaluate a single condition
   */
  private evaluateCondition(condition: Condition, index: number): boolean {
    const bar = this.data[index];

    switch (condition.type) {
      case 'indicator':
        return this.evaluateIndicatorCondition(condition as IndicatorCondition, index);

      case 'price':
        return this.evaluatePriceCondition(condition, index, bar);

      case 'time':
        // Time-based conditions not implemented in this task
        return false;

      default:
        return false;
    }
  }

  /**
   * Evaluate indicator-based condition
   */
  private evaluateIndicatorCondition(condition: IndicatorCondition, index: number): boolean {
    if (!condition.indicator) return false;

    const indicatorKey = this.getIndicatorKey(condition.indicator, condition);
    const indicatorValues = this.indicators.get(indicatorKey);

    if (!indicatorValues || index >= indicatorValues.length) {
      return false;
    }

    const currentValue = indicatorValues[index];
    if (isNaN(currentValue)) {
      return false;
    }

    // Используем параметры из стратегии для IBS условий
    let conditionValue = condition.value;
    if (condition.indicator === 'IBS') {
      if (condition.operator === '<') {
        // Условие входа - используем lowIBS из параметров
        const low = Number(this.strategy.parameters.lowIBS ?? 0.1);
        conditionValue = low;
      } else if (condition.operator === '>') {
        // Условие выхода - используем highIBS из параметров
        const high = Number(this.strategy.parameters.highIBS ?? 0.75);
        conditionValue = high;
      }
    }

    const result = this.evaluateOperator(condition.operator, currentValue, conditionValue, indicatorValues, index);

    // Debug logging for IBS conditions (only for exits)
    if (condition.indicator === 'IBS' && condition.operator === '>' && result) {
    }

    return result;
  }

  private evaluateOperator(operator: string, currentValue: number, conditionValue: number | 'dynamic' | string, indicatorValues: number[], index: number): boolean {
    const numericValue = typeof conditionValue === 'number' ? conditionValue : (conditionValue === 'dynamic' ? NaN : Number(conditionValue));
    switch (operator) {
      case '>':
        return typeof numericValue === 'number' && !isNaN(numericValue) && currentValue > numericValue;
      case '<':
        return typeof numericValue === 'number' && !isNaN(numericValue) && currentValue < numericValue;
      case '>=':
        return typeof numericValue === 'number' && !isNaN(numericValue) && currentValue >= numericValue;
      case '<=':
        return typeof numericValue === 'number' && !isNaN(numericValue) && currentValue <= numericValue;
      case '==':
        return typeof numericValue === 'number' && !isNaN(numericValue) && currentValue === numericValue;
      case 'crossover':
        if (index === 0) return false;
        if (conditionValue === 'dynamic') return false;
        return indicatorValues[index - 1] <= (numericValue as number) && currentValue > (numericValue as number);
      case 'crossunder':
        if (index === 0) return false;
        if (conditionValue === 'dynamic') return false;
        return indicatorValues[index - 1] >= (numericValue as number) && currentValue < (numericValue as number);
      default:
        return false;
    }
  }

  /**
   * Evaluate price-based condition
   */
  private evaluatePriceCondition(condition: Condition, _index: number, bar: OHLCData): boolean {
    const price = bar.close; // Use close price for simplicity

    if (condition.value === 'dynamic') {
      // Dynamic comparison (e.g., price vs moving average)
      // This would need more context about what to compare against
      return false;
    }

    if (typeof condition.value !== 'number') return false;

    switch (condition.operator) {
      case '>':
        return price > condition.value;

      case '<':
        return price < condition.value;

      case '>=':
        return price >= condition.value;

      case '<=':
        return price <= condition.value;

      case '==':
        return Math.abs(price - condition.value) < 0.01; // Allow small tolerance

      default:
        return false;
    }
  }

  /**
   * Update equity curve
   */
  private updateEquityCurve(_index: number, bar: OHLCData): void {
    let totalValue = this.currentCapital;

    // Add value of current position if any
    if (this.currentPosition) {
      const currentPrice = bar.close;
      const positionValue = this.currentPosition.quantity * currentPrice;
      totalValue += positionValue;

      // Debug: показываем расчет equity
    }

    // Calculate drawdown
    const peakValue = this.equity.length > 0
      ? Math.max(...this.equity.map(e => e.value), totalValue)
      : totalValue;

    const drawdown = peakValue > 0 ? ((peakValue - totalValue) / peakValue) * 100 : 0;

    this.equity.push({
      date: bar.date,
      value: totalValue,
      drawdown
    });
  }



  /**
   * Calculate all required indicators
   */
  private calculateIndicators(): void {
    const closePrices = this.data.map(bar => bar.close);

    // Calculate indicators based on strategy conditions
    const allConditions = [...this.strategy.entryConditions, ...this.strategy.exitConditions];


    allConditions.forEach(condition => {
      if (condition.type === 'indicator' && condition.indicator) {
        const key = this.getIndicatorKey(condition.indicator, condition);

        if (!this.indicators.has(key)) {
          const values = this.calculateIndicatorValues(condition.indicator, condition as IndicatorCondition);
          this.indicators.set(key, values);
        }
      }
    });

    // Always calculate basic indicators for context (only if we have enough data)
    if (this.data.length >= 20 && !this.indicators.has('SMA_20')) {
      this.indicators.set('SMA_20', IndicatorEngine.calculateSMA(closePrices, 20));
    }
    if (this.data.length >= 15 && !this.indicators.has('RSI_14')) {
      this.indicators.set('RSI_14', IndicatorEngine.calculateRSI(closePrices, 14));
    }
    if (!this.indicators.has('IBS')) {
      this.indicators.set('IBS', IndicatorEngine.calculateIBS(this.data));
    }
  }

  /**
   * Calculate indicator values based on type and parameters
   */
  private calculateIndicatorValues(indicatorType: string, condition: IndicatorCondition): number[] {
    const closePrices = this.data.map(bar => bar.close);

    switch (indicatorType) {
      case 'SMA': {
        const smaPeriod = this.getIndicatorPeriod(condition, 20);
        if (smaPeriod > this.data.length) {
          return new Array(this.data.length).fill(NaN);
        }
        return IndicatorEngine.calculateSMA(closePrices, smaPeriod);
      }

      case 'EMA': {
        const emaPeriod = this.getIndicatorPeriod(condition, 20);
        if (emaPeriod > this.data.length) {
          return new Array(this.data.length).fill(NaN);
        }
        return IndicatorEngine.calculateEMA(closePrices, emaPeriod);
      }

      case 'RSI': {
        const rsiPeriod = this.getIndicatorPeriod(condition, 14);
        if (rsiPeriod + 1 > this.data.length) {
          return new Array(this.data.length).fill(NaN);
        }
        return IndicatorEngine.calculateRSI(closePrices, rsiPeriod);
      }

      case 'IBS':
        return IndicatorEngine.calculateIBS(this.data);

      default:
        return new Array(this.data.length).fill(NaN);
    }
  }

  /**
   * Get indicator period from strategy parameters or use default
   */
  private getIndicatorPeriod(condition: Partial<IndicatorCondition>, defaultPeriod: number): number {
    // Try to get period from strategy parameters
    const parameterName = `${condition.indicator?.toLowerCase()}Period`;
    const period = this.strategy.parameters[parameterName];

    if (typeof period === 'number' && period > 0) {
      return period;
    }

    return defaultPeriod;
  }

  /**
   * Generate unique key for indicator caching
   */
  private getIndicatorKey(indicatorType: string, condition: Partial<IndicatorCondition>): string {
    if (indicatorType === 'IBS') {
      return 'IBS';
    }
    const period = this.getIndicatorPeriod(condition as any, 20);
    return `${indicatorType}_${period}`;
  }

  /**
   * Validate inputs
   */
  private validateInputs(): void {
    if (!this.data || this.data.length === 0) {
      throw new Error('Market data is required for backtesting');
    }

    if (!this.strategy) {
      throw new Error('Strategy is required for backtesting');
    }

    if (this.strategy.riskManagement.initialCapital <= 0) {
      throw new Error('Initial capital must be greater than 0');
    }

    // Validate data integrity - now accepts TradingDate strings
    for (let i = 0; i < this.data.length; i++) {
      const bar = this.data[i];

      const hasValidDate = typeof bar.date === 'string' ? isValidTradingDate(bar.date) : ((bar.date as any) instanceof Date && !isNaN((bar.date as any).getTime()));
      if (!hasValidDate || bar.open == null || bar.high == null || bar.low == null || bar.close == null) {
        throw new Error(`Invalid data at index ${i}: missing required fields`);
      }

      const numericFields = [bar.open, bar.high, bar.low, bar.close];
      if (!numericFields.every(v => typeof v === 'number' && isFinite(v))) {
        throw new Error(`Invalid data at index ${i}: non-numeric price values`);
      }

      // Check for price relationships with a small tolerance for floating point errors
      const epsilon = 0.000001;
      if (bar.high < bar.low - epsilon) {
         throw new Error(`Invalid data at index ${i}: high < low`);
      }
      if (bar.close < bar.low - epsilon || bar.close > bar.high + epsilon) {
         // Log warning instead of error for close outside high/low, as some data providers might have adjustments
         console.warn(`Data warning at index ${i}: close price ${bar.close} outside high/low range [${bar.low}, ${bar.high}]`);
      }
    }

    // Debug: проверяем интервалы данных
    if (this.data.length >= 5) {
      const intervals = [];
      for (let i = 1; i < Math.min(10, this.data.length); i++) {
        const daysDiff = daysBetweenTradingDates(this.data[i - 1].date, this.data[i].date);
        intervals.push(daysDiff);
      }

      const avgInterval = intervals.reduce((sum, val) => sum + val, 0) / intervals.length;

      if (avgInterval > 5) {
        console.warn(`⚠️ WARNING: Data appears to be weekly (avg ${avgInterval.toFixed(1)} days between bars)!`);
      }
    }
  }

  /**
   * Log IBS statistics for debugging
   */
  private logIBSStatistics(): void {
    const ibsKey = this.getIndicatorKey('IBS', { type: 'indicator', indicator: 'IBS', operator: '<', value: 0.1 } as any);
    const ibsValues = this.indicators.get(ibsKey);
    if (!ibsValues) return;

    const validIBS = ibsValues.filter(v => !isNaN(v));
    if (validIBS.length === 0) return;

    const highThreshold = Number(this.strategy.parameters.highIBS ?? 0.75);

    // Проверим последовательности
    let consecutiveHigh = 0;
    let maxConsecutiveHigh = 0;
    for (const ibs of validIBS) {
      if (ibs > highThreshold) {
        consecutiveHigh++;
        maxConsecutiveHigh = Math.max(maxConsecutiveHigh, consecutiveHigh);
      } else {
        consecutiveHigh = 0;
      }
    }
  }

  /**
   * Calculate volatility at given index
   */
  private calculateVolatility(index: number): number {
    const period = Math.min(20, index + 1);
    const startIndex = Math.max(0, index - period + 1);

    const returns = [];
    for (let i = startIndex + 1; i <= index; i++) {
      // Add bounds checking to prevent array access errors
      if (i - 1 < 0 || i >= this.data.length) continue;

      const prevClose = this.data[i - 1].close;
      const currentClose = this.data[i].close;
      returns.push(Math.log(currentClose / prevClose));
    }

    if (returns.length === 0) return 0;

    const mean = returns.reduce((sum, r) => sum + r, 0) / returns.length;
    const variance = returns.reduce((sum, r) => sum + Math.pow(r - mean, 2), 0) / returns.length;

    return Math.sqrt(variance * 252); // Annualized volatility
  }

  /**
   * Get indicator values at given index
   */
  private getIndicatorValues(index: number): Record<string, number> {
    const values: Record<string, number> = {};

    for (const [name, data] of this.indicators) {
      if (data[index] !== undefined) {
        values[name] = data[index] as number;
      }
    }

    return values;
  }

  /**
   * Calculate trend at given index
   */
  private calculateTrend(index: number): string {
    // Add comprehensive bounds checking
    if (index < 10 || index >= this.data.length || index - 10 < 0) return 'sideways';

    const currentPrice = this.data[index].close;
    const pastPrice = this.data[index - 10].close;

    if (currentPrice > pastPrice * 1.02) return 'up';
    if (currentPrice < pastPrice * 0.98) return 'down';
    return 'sideways';
  }

  /**
   * Calculate performance metrics using the dedicated metrics calculator
   */
  private calculatePerformanceMetrics(): PerformanceMetrics {
    const metricsCalculator = new MetricsCalculator(
      this.trades,
      this.equity,
      this.strategy.riskManagement.initialCapital,
      this.data // Use market data as benchmark for now
    );

    return metricsCalculator.calculateAllMetrics();
  }




}

/**
 * Simple backtest runner for the simplified app
 */
export function runBacktest(data: OHLCData[], strategy: Strategy): BacktestResult {

  // Используем чистый бэктест только для IBS стратегии
  const engine = new CleanBacktestEngine(data, strategy);
  return engine.runBacktest();
}
